name: Build

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest  
    architecture: ['x64']
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
      with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-python
            mingw-w64-x86_64-setuptools
      - name: install 
        run: |
          cd htslib
          autoheader && autoconf
          ./configure --enable-s3 --disable-lzma --disable-bz2
